### ISSUE TITLE
Plugin secretstore incompatible with NetBox 3.5

### ISSUE THREAD

**Issue by nomaster** [ffddorf/netbox-heroku-docker#60]
> django.core.exceptions.ImproperlyConfigured: Plugin netbox_secretstore requires NetBox maximum version 3.4.99.

**Comment by mraerino** [comment]
Looks like it [got deprecated](https://github.com/DanSheps/netbox-secretstore#discontinuation-of-plugin) in favor of https://github.com/Onemind-Services-LLC/netbox-secrets

**Comment by mraerino** [comment]
i'm going to attempt the migration

**Comment by mraerino** [comment]
Looks like we need to wait for https://github.com/Onemind-Services-LLC/netbox-secrets/pull/54 to land
